import { ThemeConfig, ThemeId } from "@/types";

export const THEME_REGISTRY: Record<ThemeId, ThemeConfig> = {
  midnight: {
    id: "midnight",
    name: "Midnight",
    background: "#0D0D1A",
    surface: "#1A1A2E",
    primaryText: "#FFFFFF",
    secondaryText: "#8B8BA7",
    accent: "#7C3AED",
    barBackground: "#2D2D4A",
    barFill: "#7C3AED",
    gradientFrom: "#0D0D1A",
    gradientTo: "#1E1040",
  },
  sunset: {
    id: "sunset",
    name: "Sunset",
    background: "#1A0A00",
    surface: "#2D1500",
    primaryText: "#FFF4EC",
    secondaryText: "#E8A87C",
    accent: "#FF6B35",
    barBackground: "#3D2010",
    barFill: "#FF6B35",
    gradientFrom: "#2D0A00",
    gradientTo: "#8B2500",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    background: "#03045E",
    surface: "#023E8A",
    primaryText: "#CAF0F8",
    secondaryText: "#90E0EF",
    accent: "#00B4D8",
    barBackground: "#0077B6",
    barFill: "#00B4D8",
    gradientFrom: "#03045E",
    gradientTo: "#0077B6",
  },
  forest: {
    id: "forest",
    name: "Forest",
    background: "#071A07",
    surface: "#122612",
    primaryText: "#E8F5E9",
    secondaryText: "#81C784",
    accent: "#4CAF50",
    barBackground: "#1E3A1E",
    barFill: "#4CAF50",
    gradientFrom: "#071A07",
    gradientTo: "#1A3A1A",
  },
  neon: {
    id: "neon",
    name: "Neon",
    background: "#050505",
    surface: "#0E0E0E",
    primaryText: "#00FF87",
    secondaryText: "#00CC6A",
    accent: "#00FF87",
    barBackground: "#141414",
    barFill: "#00FF87",
    gradientFrom: "#050505",
    gradientTo: "#0A1A0A",
  },
  candy: {
    id: "candy",
    name: "Candy",
    background: "#FF4785",
    surface: "#FF6BA0",
    primaryText: "#FFFFFF",
    secondaryText: "#FFD6E8",
    accent: "#FFFFFF",
    barBackground: "#FF6BA0",
    barFill: "#FFFFFF",
    gradientFrom: "#FF4785",
    gradientTo: "#FF85C8",
  },
  "minimal-dark": {
    id: "minimal-dark",
    name: "Minimal Dark",
    background: "#111111",
    surface: "#1A1A1A",
    primaryText: "#FFFFFF",
    secondaryText: "#777777",
    accent: "#FFFFFF",
    barBackground: "#2A2A2A",
    barFill: "#FFFFFF",
    gradientFrom: "#111111",
    gradientTo: "#1A1A1A",
  },
  "minimal-light": {
    id: "minimal-light",
    name: "Minimal Light",
    background: "#FAFAFA",
    surface: "#F0F0F0",
    primaryText: "#111111",
    secondaryText: "#777777",
    accent: "#111111",
    barBackground: "#E0E0E0",
    barFill: "#111111",
    gradientFrom: "#FAFAFA",
    gradientTo: "#F0F0F0",
  },
};

export const THEME_ORDER: ThemeId[] = [
  "midnight",
  "sunset",
  "ocean",
  "forest",
  "neon",
  "candy",
  "minimal-dark",
  "minimal-light",
];
