import { ThemeConfig, ThemeId } from "@/types";

export const THEME_REGISTRY: Record<ThemeId, ThemeConfig> = {
  midnight: {
    id: "midnight",
    name: "Midnight",
    background: "#0D0D1A",
    surface: "#1A1A2E",
    primaryText: "#FFFFFF",
    secondaryText: "#8B8BA7",
    accent: "#7C3AED",
    barBackground: "#2D2D4A",
    barFill: "#7C3AED",
    gradientFrom: "#0D0D1A",
    gradientTo: "#1A1A2E",
  },
  sunset: {
    id: "sunset",
    name: "Sunset",
    background: "#1A0A0A",
    surface: "#2D1515",
    primaryText: "#FFF4EC",
    secondaryText: "#D4927A",
    accent: "#FF6B35",
    barBackground: "#3D2020",
    barFill: "#FF6B35",
    gradientFrom: "#FF6B35",
    gradientTo: "#F7C59F",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    background: "#03045E",
    surface: "#023E8A",
    primaryText: "#CAF0F8",
    secondaryText: "#90E0EF",
    accent: "#00B4D8",
    barBackground: "#0077B6",
    barFill: "#00B4D8",
    gradientFrom: "#03045E",
    gradientTo: "#023E8A",
  },
  forest: {
    id: "forest",
    name: "Forest",
    background: "#0A1F0A",
    surface: "#1A3320",
    primaryText: "#E8F5E9",
    secondaryText: "#81C784",
    accent: "#4CAF50",
    barBackground: "#2E5C35",
    barFill: "#4CAF50",
    gradientFrom: "#0A1F0A",
    gradientTo: "#1A3320",
  },
  neon: {
    id: "neon",
    name: "Neon",
    background: "#0A0A0A",
    surface: "#111111",
    primaryText: "#00FF87",
    secondaryText: "#00CC6A",
    accent: "#00FF87",
    barBackground: "#1A1A1A",
    barFill: "#00FF87",
    gradientFrom: "#0A0A0A",
    gradientTo: "#111111",
  },
  candy: {
    id: "candy",
    name: "Candy",
    background: "#FF6B9D",
    surface: "#FF8FB1",
    primaryText: "#FFFFFF",
    secondaryText: "#FFD6E5",
    accent: "#FF4D6D",
    barBackground: "#FF8FB1",
    barFill: "#FFFFFF",
    gradientFrom: "#FF6B9D",
    gradientTo: "#FFADC5",
  },
  "minimal-dark": {
    id: "minimal-dark",
    name: "Minimal Dark",
    background: "#111111",
    surface: "#1E1E1E",
    primaryText: "#FFFFFF",
    secondaryText: "#888888",
    accent: "#FFFFFF",
    barBackground: "#2E2E2E",
    barFill: "#FFFFFF",
    gradientFrom: "#111111",
    gradientTo: "#1E1E1E",
  },
  "minimal-light": {
    id: "minimal-light",
    name: "Minimal Light",
    background: "#FFFFFF",
    surface: "#F5F5F5",
    primaryText: "#111111",
    secondaryText: "#666666",
    accent: "#111111",
    barBackground: "#E0E0E0",
    barFill: "#111111",
    gradientFrom: "#FFFFFF",
    gradientTo: "#F5F5F5",
  },
};

export const THEME_ORDER: ThemeId[] = [
  "midnight",
  "sunset",
  "ocean",
  "forest",
  "neon",
  "candy",
  "minimal-dark",
  "minimal-light",
];
